http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

http.cors.enabled: true
http.cors.allow-origin: '*'
http.cors.allow-headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With
http.cors.allow-credentials: true
